[package]
name = "ahc005"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.8"
rand = { version = "0.7.3", features = ["small_rng"] }
bitset-fixed = "0.1.0"
